## TUPLE

In [2]:
# Membuat tuple
t1 = (2, 3)
t2 = (4, 'abc')
t3 = tuple('kacang')

print(t1)
print(t2)
print(t3)

(2, 3)
(4, 'abc')
('k', 'a', 'c', 'a', 'n', 'g')


In [3]:
numbers = (1, 2, 3, 4)

a, b, c, d = numbers
print(a, b, c, d)

1 2 3 4


In [4]:
resolutions = (
    (3, 4),
    (16, 9)
)
print(resolutions[0])
print(resolutions[1])

print(resolutions[0][0], resolutions[0][1])

(3, 4)
(16, 9)
3 4


## LIST

In [6]:
## Membuat List
list1 = [10, -1, 13.7]
list2 = ["apel", "pisang", "mangga"]
list3 = [-75, "kartu", True]
list4 = list("rumput")

print(list1)
print(list2)
print(list3)
print(list4)

[10, -1, 13.7]
['apel', 'pisang', 'mangga']
[-75, 'kartu', True]
['r', 'u', 'm', 'p', 'u', 't']


In [16]:
names = ['andi', 'budi', 'cindy']

#append
names.append('dony')
print(names)

#insert
names.insert(1, 'x')
print(names)

#remove
names.remove('cindy')
print(names)

#pop
names.pop(-1)
print(names)

['andi', 'budi', 'cindy', 'dony']
['andi', 'x', 'budi', 'cindy', 'dony']
['andi', 'x', 'budi', 'dony']
['andi', 'x', 'budi']


In [18]:
pets = ['cat', 'dog']
new_pets = ['beaver', 'capybara']

#print(pets + new_pers)
pets.extend(new_pets)
print(pets)

['cat', 'dog', 'beaver', 'capybara']


In [22]:
pets.sort()
print(pets)

sorted(new_pets)

['beaver', 'capybara', 'cat', 'dog']


['beaver', 'capybara']

In [24]:
#print(pets[0])
#print(pets[1])

for pet in pets:
    print(pet, end=" ")
print()

beaver capybara cat dog 


In [26]:
for i in range(0, 4):
    print(pets[i], end=" ")
print()

beaver capybara cat dog 


In [28]:
index = 0
while (index < len(pets)):
    print(pets[index], end=" ")
    index +=1
print()

beaver capybara cat dog 


In [46]:
# copying list
toppings = ['pineapple', 'pepperoni', 'tomato']
my_copy_toppings = toppings [:]

my_copy_toppings.pop(0)
print(toppings)
print(my_copy_toppings)

['pineapple', 'pepperoni', 'tomato']
['pepperoni', 'tomato']


## SET

In [31]:
# Membuat set
s1 = {'ayam', 'bebek', 'ayam', 'kuda'}
s2 = set(list('kacang'))

print(s1)
print(s2)

{'bebek', 'ayam', 'kuda'}
{'n', 'c', 'g', 'k', 'a'}


In [33]:
s3 = set('matematika')
s4 = set('statistika')
s5 = set('aktuaria')

print(s3)
print(s4)
print(s5)

{'t', 'e', 'i', 'm', 'k', 'a'}
{'t', 'i', 'k', 'a', 's'}
{'t', 'i', 'u', 'r', 'k', 'a'}


In [35]:
print(s3 & s4) # irisan / intersection

{'k', 't', 'a', 'i'}


In [37]:
print(s3 | s4) # gabungan / union

{'t', 'e', 'i', 'm', 'k', 'a', 's'}


In [39]:
#subset
print(s4 <= s5)
print( {3, 4} <= {1, 2, 3, 4, 5})

False
True


In [41]:
#super set
print(s4 >= s3)
print( {3, 4, 5, 6, 7, 8} >= {7, 4})

False
True


## NUMPY ARRAY

In [49]:
import numpy as np

In [51]:
array1 = np.zeros(5)
array2 = np.ones(3)

print(array1)
print(array2)
print(type(array1))
print(type(array2))

[0. 0. 0. 0. 0.]
[1. 1. 1.]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [55]:
array3 = np.array([0, 0, 0, 0, 0], dtype='float')
print(array3)

array4 = np.array([10, -5, 2, 17])
print(array4)

[0. 0. 0. 0. 0.]
[10 -5  2 17]


In [67]:
array5 = np.empty(8)
print(array5)

[17.6  24.3   2.5   3.75  5.    6.25  7.5   8.75]


In [61]:
array5[0] = -17.6
array5[1] = 24.3

for i in range(2, len(array5)): # dari i=2 sampai i=7
    array5[i] = 5*i/4
print(array5)

[-17.6   24.3    2.5    3.75   5.     6.25   7.5    8.75]


In [69]:
boston_price_list = [9.99, 7.99, 7.49, 7.00, 6.29, 4.99]
london_price_list = [7.5, 5, 4.4, 5, 3.75, 2.25]

In [71]:
boston_price_list + london_price_list

[9.99, 7.99, 7.49, 7.0, 6.29, 4.99, 7.5, 5, 4.4, 5, 3.75, 2.25]

In [73]:
boston_price_list - london_price_list

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [75]:
boston_price_array = np.array(boston_price_list)
london_price_array = np.array(london_price_list)
differences = boston_price_array - london_price_array
differences

array([2.49, 2.99, 3.09, 2.  , 2.54, 2.74])

In [77]:
boston_price_array + london_price_array

array([17.49, 12.99, 11.89, 12.  , 10.04,  7.24])

In [79]:
boston_price_array * london_price_array

array([74.925 , 39.95  , 32.956 , 35.    , 23.5875, 11.2275])

In [81]:
boston_price_array / london_price_array

array([1.332     , 1.598     , 1.70227273, 1.4       , 1.67733333,
       2.21777778])