In [4]:
import numpy as np

In [6]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1.5, 2.5, 5, 6, 7])

print(a)
print(b)

[1 2 3 4 5]
[1.5 2.5 5.  6.  7. ]


In [7]:
c = np.arange(1, 10, 2)

print(c)

c_2 = np.arange(1, 10, 0.5)
print(c_2)

[1 3 5 7 9]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [9]:
d = np.linspace(1, 10, 4)

print(d)

[ 1.  4.  7. 10.]


In [10]:
# array multidmensi / matrix

e = np.array( [ (1, 2, 3) ,
                (4, 5, 6)])

print(e)
print(e.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [11]:
# matrix dengan nilai nol
f = np.zeros((5, 5))
print(f)
# matrix dengan nilai satu
g = np.ones((5, 5))
print(g)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
h1 = np.identity(5)

print(h1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Operasi Matematika

In [12]:
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]

anp = np.array([1, 2, 3, 4, 5])
bnp = np.array([6, 7, 8, 9, 10])

anp + bnp

array([ 7,  9, 11, 13, 15])

In [14]:
anp - bnp

array([-5, -5, -5, -5, -5])

In [15]:
anp * bnp

array([ 6, 14, 24, 36, 50])

In [16]:
anp / bnp

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [18]:
anp**2

array([ 1,  4,  9, 16, 25])

In [29]:
c = np.array(([1, 2, 3], 
              [4, 5, 6]))
d = np.array(([7, 8, 9], 
              [-1, -2, -3]))

add = c + d
mult = c * d
print(add)
print(mult)

[[ 8 10 12]
 [ 3  3  3]]
[[  7  16  27]
 [ -4 -10 -18]]


## Perkalian Dot Matrix

In [21]:
a = np.array(([1, 2],
             [3, 4]))

b = np.ones([2, 2])

print("matrix a: ")
print(a)
print()

print("matrix b: ")
print(a)
print()

# perkalian matrix
c1 = np.dot(a, b)
c2 = a.dot(b)

print("matrix c1:")
print(c1)
print()

print("matrix c2:")
print(c2)
print()

matrix a: 
[[1 2]
 [3 4]]

matrix b: 
[[1 2]
 [3 4]]

matrix c1:
[[3. 3.]
 [7. 7.]]

matrix c2:
[[3. 3.]
 [7. 7.]]



## Shape manipulation

In [23]:
a = np.array((
    [1, 2, 3], 
    [4, 5, 6]
))

print("matrix a dengan ukuran dari a: ", a.shape)
print(a)
print()

# transpose matrix
print('transpose matrix dari a: ')
print(a.transpose())
print(a.shape)
print()

# transpose matrix
print('transpose matrix dari a transpose: ')
a_transpose = np.transpose(a)
print(a_transpose.shape)
print()

matrix a dengan ukuran dari a:  (2, 3)
[[1 2 3]
 [4 5 6]]

transpose matrix dari a: 
[[1 4]
 [2 5]
 [3 6]]
(2, 3)

transpose matrix dari a transpose: 
(3, 2)



In [27]:
a = np.array([ 
    (2,4), 
    (3,5)
])
print(a)
print()
#invers matrix
a_inv = np.linalg.inv(a)
print(a_inv)
print()

#determinan matrix
det_a = np.linalg.det(a)
det_a_inv = np.linalg.det(a_inv)
print(det_a)
print(det_a_inv)

[[2 4]
 [3 5]]

[[-2.5  2. ]
 [ 1.5 -1. ]]

-2.0000000000000004
-0.4999999999999996


## Contoh SPLDV

In [26]:
# 2a + 3b = 23 and a + 2b = 14

A = np.array([(2,3),
              (1, 2)])

Y = np.array([23, 14])

print(A)
print(Y)
print()

A_inv = np.linalg.inv(A)

# menyelesaikan persamaan linear
X1 = np.dot(A_inv, Y)
print(X1)
print()

# cara lain 
X2 = np.linalg.solve(A, Y)
print(X2)

[[2 3]
 [1 2]]
[23 14]

[4. 5.]

[4. 5.]


## Latihan

In [3]:
import numpy as np

# Soal 1
matrix1 = np.array([[1/2, 2/3], [-3/4, -5/2]])
matrix2 = np.array([[7, 1], [-1, 0]])
hasil1 = -2 * matrix1 + matrix2
print("Hasil Soal 1:\n", hasil1)

# Soal 2
matrix3 = np.array([[15, 30], [10, 25]])
matrix4 = np.array([[4, -1], [2, -2]])
hasil2 = (2/5) * matrix3 + matrix4
print("\nHasil Soal 2:\n", hasil2)

# Soal 3
matrix5 = np.array([[-2, 6, 3, -2], [3, 4, 2, 1]])
matrix6 = np.array([[3, 2], [-2, 1], [-1, -4], [4, 3]])
hasil3 = np.dot(matrix5, matrix6)
print("\nHasil Soal 3:\n", hasil3)

# Soal 4
matrix7 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix8 = np.array([[1, 3, 2], [7, -1, 3], [-2, 3, -2]])
hasil4 = np.dot(matrix7, matrix8)
print("\nHasil Soal 4:\n", hasil4)

# Soal 5
matrix9 = np.array([[2, -5, 7], [-9, 9, -9], [3, -2, 1]])
inverse_matrix9 = np.linalg.inv(matrix9)
print("\nHasil Invers Soal 5:\n", inverse_matrix9)

# Soal 6
A = np.array([[2, -3], [1, 2]])
Y = np.array([8, -3])
solution = np.linalg.solve(A, Y)
print("\nHasil Penyelesaian Soal 6:\n", solution)


Hasil Soal 1:
 [[ 6.         -0.33333333]
 [ 0.5         5.        ]]

Hasil Soal 2:
 [[10. 11.]
 [ 6.  8.]]

Hasil Soal 3:
 [[-29 -16]
 [  3   5]]

Hasil Soal 4:
 [[ 9 10  2]
 [27 25 11]
 [45 40 20]]

Hasil Invers Soal 5:
 [[-1.         -1.         -2.        ]
 [-2.         -2.11111111 -5.        ]
 [-1.         -1.22222222 -3.        ]]

Hasil Penyelesaian Soal 6:
 [ 1. -2.]
